theme: jekyll-theme-cayman
markdown: kramdown
title: MakerGram Legal
email: contact@makergram.com
description: >- # this means to ignore newlines until "baseurl:"
  MakerGram Legal Documents
twitter_username: Maker_Gram
github_username:  MakerGram